Dribbble/Controllers/ShotController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dribbble.Models;

namespace Dribbble.Controllers
{
    public class ShotController : Controller
    {
        private ShotRepository shotRepo = new ShotRepository();
        // GET: Shot
        public ActionResult Index()
        {
            return View(shotRepo.GetAll());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shot s = shotRepo.GetByID((int) id);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Models.Shot shot)
        {
            if (Request != null)
            {
                if (shot.file != null)
                {
                    string fileName = Path.GetFileName(shot.file.FileName);
                    if (fileName != null)
                    {
                        var path = Path.Combine(Server.MapPath("~/Content/uploads"), fileName);
                        shot.file.SaveAs(path);

                        shot.ImageURL = fileName;
                        shot.AccountID = Convert.ToInt32(User.Identity.Name);

                        shotRepo.Insert(shot);

                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            return View();
        }
    }
}

Dribbble/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dribbble", "Index", "Shot", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shots", "Index", "Shot")</li>
                    <li>@Html.ActionLink("Designers", "About", "Home")</li>
                    <li>@Html.ActionLink("Teams", "Contact", "Home")</li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fontys Hogeschool ICT</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>